version: '3'
services:
  generate:
    image: svlentink/yaml-resume
    environment:
      COMPILE_LANGUAGE: dutch
    volumes:
      - $PWD/generated:/output
      - $PWD/content:/content:ro
#  build:
#    image: svlentink/texlive-full
#    volumes:
#      - $PWD:/data
#    command: texi2pdf --tidy --shell-escape --output=/data/resume.pdf /data/resume.tex