aggregations:
  timespan:
    - start #points to value
    - ' -> '
    - end #also a value
    - ', ' # string
    - hours #value in experience file again
    - 'h p/w' #str
  organization:
    - company
    - ', '
    - city

exp-column-percentage: [20,80]
exp-order:
  - sector
  - organization
  - title
  - timespan
  - employment
  - projecturl
  - desc
  - tech

