aggregations:
  timespan:
    - start #points to value
    - ' -> '
    - end #also a value
    - ', ' # string
    - hours #value in experience file again
    - 'h p/w' #str
  organization:
    - company
    - ', '
    - city

exp-column-percentage: [20,80]
exp-order:
  - sector
  - organization
  - title
  - timespan
  - employment
  - projecturl
  - desc
  - activities
  - tech

edu-column-percentage: [15,27,27,8,8,15]
edu-order:
  - type
  - title
  - institution
  - start
  - end
  - status

