aggregations:
  timespan:
    - start #points to value
    - ' -> '
    - end #also a value
    - ', ' # string
    - hours #value in experience file again
    - 'h p/w' #str
  fromto:
    - start
    - '-'
    - end
  organization:
    - company
    - ', '
    - city

exp-column-percentage: [20,80]
exp-order:
  - sector
  - organization
  - title
  - timespan
  - employment
  - projecturl
  - desc
  - activities
  - tech

edu-column-percentage: [15,30,31,14,10]
edu-order:
  - type
  - title
  - institution
  - fromto
  - status

eduoth-column-percentage: [15,35,31,19]
eduoth-order:
  - type
  - title
  - institution
  - end
